export WANDB_PROJECT=starling_ppo
deepspeed --num_gpus 8 --master_port=9901 src/train_bash.py \
    --deepspeed ./script/static/zero_stage2.json \
    --stage ppo \
    --do_train \
    --model_name_or_path openchat/openchat_3.5 \
    --overwrite_output_dir \
    --dataset ultrafeedback \
    --split train_prefs \
    --template default \
    --create_new_adapter \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --reward_model berkeley-nest/Starling-RM-7B-alpha \
    --reward_model_type full \
    --output_dir results/starling-7B-ppo \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --top_k 0 \
    --top_p 0.9 \
    --logging_steps 2 \
    --save_steps 256 \
    --learning_rate 1e-5 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --bf16 \
    --run_name='lm:openchat7b--rm:starling-7b-RM--lr:1e-5--bsize:128' \
    --report_to wandb \
    --logging_step 2 \
    --ppo_logger wandb 